# coding: utf-8

"""
    MUDBASESDK

    MUDBASE is a scalable, real-time, and secure Backend-as-a-Service (BaaS) platform  designed for modern applications. Built with custom logic, it offers fine-grained  control, extensibility, and enterprise-grade security.  ## Features - 🔐 Multi-provider authentication (30+ OAuth providers) - 📊 Real-time database with collections - 📁 File storage and management - 🔑 API key management with permissions - 🔗 Webhook system with retry logic - ⚡ Serverless functions - 💬 Multi-channel messaging (Push, Email, SMS) - 📈 Usage analytics and monitoring - 🌐 Real-time WebSocket events - 🔍 Full-text search capabilities - 💳 Billing: fiat only for project subscriptions and org BaaS checkout (platform fee split). On-chain billing is not exposed on these APIs (optional `crypto-payment-module/` in repo, not mounted by default). - 🏢 Enterprise / Phase 4: custom domains on Growth, Scale, and Enterprise (TXT DNS at `_mudbase-verify.<hostname>`); `settings.customDomainAddon` is optional (billing/legacy); dedicated DB migration script, periodic DNS recheck job, optional `infrastructureEnvironments[]` and edge/metering fields on `dedicated`. 

    The version of the OpenAPI document: 1.3.14
    Contact: support@mudbase.dev
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from mudbase.models.usage_stats_response import UsageStatsResponse

class TestUsageStatsResponse(unittest.TestCase):
    """UsageStatsResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UsageStatsResponse:
        """Test UsageStatsResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UsageStatsResponse`
        """
        model = UsageStatsResponse()
        if include_optional:
            return UsageStatsResponse(
                usage = mudbase.models.usage.Usage(
                    projects = 56, 
                    users = 56, 
                    storage = 56, 
                    bandwidth = 56, 
                    api_calls = 56, 
                    db_reads = 56, 
                    db_writes = 56, ),
                limits = mudbase.models.limits.Limits(
                    projects = 56, 
                    users = 56, 
                    storage = 56, 
                    bandwidth = 56, 
                    api_calls = 56, 
                    db_reads = 56, 
                    db_writes = 56, ),
                plan = mudbase.models.plan.Plan(
                    name = '', 
                    price = 1.337, 
                    currency = '', 
                    interval = '', 
                    features = [
                        ''
                        ], ),
                period = '',
                percentages = mudbase.models.usage_stats_response_percentages.UsageStatsResponse_percentages(
                    api_calls = 1.337, 
                    storage = 1.337, 
                    bandwidth = 1.337, )
            )
        else:
            return UsageStatsResponse(
        )
        """

    def testUsageStatsResponse(self):
        """Test UsageStatsResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
