# coding: utf-8

"""
    MUDBASESDK

    MUDBASE is a scalable, real-time, and secure Backend-as-a-Service (BaaS) platform  designed for modern applications. Built with custom logic, it offers fine-grained  control, extensibility, and enterprise-grade security.  ## Features - 🔐 Multi-provider authentication (30+ OAuth providers) - 📊 Real-time database with collections - 📁 File storage and management - 🔑 API key management with permissions - 🔗 Webhook system with retry logic - ⚡ Serverless functions - 💬 Multi-channel messaging (Push, Email, SMS) - 📈 Usage analytics and monitoring - 🌐 Real-time WebSocket events - 🔍 Full-text search capabilities - 💳 Billing: fiat only for project subscriptions and org BaaS checkout (platform fee split). On-chain billing is not exposed on these APIs (optional `crypto-payment-module/` in repo, not mounted by default). - 🏢 Enterprise / Phase 4: custom domains on Growth, Scale, and Enterprise (TXT DNS at `_mudbase-verify.<hostname>`); `settings.customDomainAddon` is optional (billing/legacy); dedicated DB migration script, periodic DNS recheck job, optional `infrastructureEnvironments[]` and edge/metering fields on `dedicated`. 

    The version of the OpenAPI document: 1.3.15
    Contact: support@mudbase.dev
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from mudbase.models.get_billing_estimate200_response import GetBillingEstimate200Response

class TestGetBillingEstimate200Response(unittest.TestCase):
    """GetBillingEstimate200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetBillingEstimate200Response:
        """Test GetBillingEstimate200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetBillingEstimate200Response`
        """
        model = GetBillingEstimate200Response()
        if include_optional:
            return GetBillingEstimate200Response(
                period = '',
                line_items = [
                    mudbase.models.get_billing_estimate_200_response_line_items_inner.getBillingEstimate_200_response_lineItems_inner(
                        resource = '', 
                        units = 1.337, 
                        amount = 1.337, 
                        currency = '', 
                        unit = '', )
                    ],
                estimated_overage_cents = 1.337,
                estimated_overage = '$12.50',
                forecast_overage_cents = 1.337,
                forecast_overage = '$38.00',
                message = '',
                spend_limits = mudbase.models.get_billing_estimate_200_response_spend_limits.getBillingEstimate_200_response_spendLimits(
                    soft_limit_cents = 1.337, 
                    hard_limit_cents = 1.337, 
                    spend_blocked = True, )
            )
        else:
            return GetBillingEstimate200Response(
        )
        """

    def testGetBillingEstimate200Response(self):
        """Test GetBillingEstimate200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
