# coding: utf-8

"""
    MUDBASESDK

    MUDBASE is a scalable, real-time, and secure Backend-as-a-Service (BaaS) platform  designed for modern applications. Built with custom logic, it offers fine-grained  control, extensibility, and enterprise-grade security.  ## Features - 🔐 Multi-provider authentication (30+ OAuth providers) - 📊 Real-time database with collections - 📁 File storage and management - 🔑 API key management with permissions - 🔗 Webhook system with retry logic - ⚡ Serverless functions - 💬 Multi-channel messaging (Push, Email, SMS) - 📈 Usage analytics and monitoring - 🌐 Real-time WebSocket events - 🔍 Full-text search capabilities - 💳 Billing: fiat only for project subscriptions and org BaaS checkout (platform fee split). On-chain billing is not exposed on these APIs (optional `crypto-payment-module/` in repo, not mounted by default). - 🏢 Enterprise / Phase 4: custom domains on Growth, Scale, and Enterprise (TXT DNS at `_mudbase-verify.<hostname>`); `settings.customDomainAddon` is optional (billing/legacy); dedicated DB migration script, periodic DNS recheck job, optional `infrastructureEnvironments[]` and edge/metering fields on `dedicated`. 

    The version of the OpenAPI document: 1.3.14
    Contact: support@mudbase.dev
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from mudbase.models.update_api_key200_response import UpdateApiKey200Response

class TestUpdateApiKey200Response(unittest.TestCase):
    """UpdateApiKey200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UpdateApiKey200Response:
        """Test UpdateApiKey200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UpdateApiKey200Response`
        """
        model = UpdateApiKey200Response()
        if include_optional:
            return UpdateApiKey200Response(
                message = '',
                api_key = mudbase.models.api_key.ApiKey(
                    _id = '', 
                    name = '', 
                    project = mudbase.models.project_summary.ProjectSummary(
                        _id = '', 
                        name = '', 
                        slug = '', ), 
                    permissions = [
                        mudbase.models.api_key_permission.ApiKeyPermission(
                            resource = 'auth', 
                            actions = [
                                'create'
                                ], )
                        ], 
                    rate_limit = mudbase.models.rate_limit.RateLimit(
                        requests = 56, 
                        window = 56, ), 
                    usage = mudbase.models.api_key_usage.ApiKeyUsage(
                        requests = 56, 
                        last_used = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), ), 
                    is_active = True, 
                    expires_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    created_by = mudbase.models.user_summary.UserSummary(
                        _id = '', 
                        first_name = '', 
                        last_name = '', 
                        email = '', ), 
                    created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
            )
        else:
            return UpdateApiKey200Response(
        )
        """

    def testUpdateApiKey200Response(self):
        """Test UpdateApiKey200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
