# coding: utf-8

"""
    MUDBASESDK

    MUDBASE is a scalable, real-time, and secure Backend-as-a-Service (BaaS) platform  designed for modern applications. Built with custom logic, it offers fine-grained  control, extensibility, and enterprise-grade security.  ## Features - 🔐 Multi-provider authentication (30+ OAuth providers) - 📊 Real-time database with collections - 📁 File storage and management - 🔑 API key management with permissions - 🔗 Webhook system with retry logic - ⚡ Serverless functions - 💬 Multi-channel messaging (Push, Email, SMS) - 📈 Usage analytics and monitoring - 🌐 Real-time WebSocket events - 🔍 Full-text search capabilities - 💳 Billing: fiat only for project subscriptions and org BaaS checkout (platform fee split). On-chain billing is not exposed on these APIs (optional `crypto-payment-module/` in repo, not mounted by default). - 🏢 Enterprise / Phase 4: custom domains on Growth, Scale, and Enterprise (TXT DNS at `_mudbase-verify.<hostname>`); `settings.customDomainAddon` is optional (billing/legacy); dedicated DB migration script, periodic DNS recheck job, optional `infrastructureEnvironments[]` and edge/metering fields on `dedicated`. 

    The version of the OpenAPI document: 1.3.12
    Contact: support@mudbase.dev
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from mudbase.models.dashboard_overview_data_latency import DashboardOverviewDataLatency

class TestDashboardOverviewDataLatency(unittest.TestCase):
    """DashboardOverviewDataLatency unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DashboardOverviewDataLatency:
        """Test DashboardOverviewDataLatency
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DashboardOverviewDataLatency`
        """
        model = DashboardOverviewDataLatency()
        if include_optional:
            return DashboardOverviewDataLatency(
                scope = 'project_openapi_doc',
                avg_ms_today = 56,
                avg_ms7d = 56,
                latency_samples_today = 56,
                latency_needs_traffic = True,
                interpretation = '',
                instance_rollup = mudbase.models.dashboard_overview_data_latency_instance_rollup.DashboardOverviewData_latency_instanceRollup(
                    scope = 'instance_recent', 
                    p50_ms = 56, 
                    p95_ms = 56, 
                    p99_ms = 56, 
                    mean_ms = 56, 
                    samples_approx = 56, 
                    templates_tracked = 56, ),
                top_routes_by_impact_hint = [
                    mudbase.models.dashboard_overview_data_latency_top_routes_by_impact_hint_inner.DashboardOverviewData_latency_topRoutesByImpactHint_inner(
                        route_key = '', 
                        p50_ms = 56, 
                        p95_ms = 56, 
                        count = 56, 
                        impact_score = 56, )
                    ]
            )
        else:
            return DashboardOverviewDataLatency(
        )
        """

    def testDashboardOverviewDataLatency(self):
        """Test DashboardOverviewDataLatency"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
