# coding: utf-8

"""
    MUDBASESDK

    MUDBASE is a scalable, real-time, and secure Backend-as-a-Service (BaaS) platform  designed for modern applications. Built with custom logic, it offers fine-grained  control, extensibility, and enterprise-grade security.  ## Features - 🔐 Multi-provider authentication (30+ OAuth providers) - 📊 Real-time database with collections - 📁 File storage and management - 🔑 API key management with permissions - 🔗 Webhook system with retry logic - ⚡ Serverless functions - 💬 Multi-channel messaging (Push, Email, SMS) - 📈 Usage analytics and monitoring - 🌐 Real-time WebSocket events - 🔍 Full-text search capabilities - 💳 Billing: fiat only for project subscriptions and org BaaS checkout (platform fee split). On-chain billing is not exposed on these APIs (optional `crypto-payment-module/` in repo, not mounted by default). - 🏢 Enterprise / Phase 4: custom domains on Growth, Scale, and Enterprise (TXT DNS at `_mudbase-verify.<hostname>`); `settings.customDomainAddon` is optional (billing/legacy); dedicated DB migration script, periodic DNS recheck job, optional `infrastructureEnvironments[]` and edge/metering fields on `dedicated`. 

    The version of the OpenAPI document: 1.3.14
    Contact: support@mudbase.dev
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from mudbase.models.get_project_users200_response import GetProjectUsers200Response

class TestGetProjectUsers200Response(unittest.TestCase):
    """GetProjectUsers200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetProjectUsers200Response:
        """Test GetProjectUsers200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetProjectUsers200Response`
        """
        model = GetProjectUsers200Response()
        if include_optional:
            return GetProjectUsers200Response(
                users = [
                    mudbase.models.get_organization_users_200_response_users_inner.getOrganizationUsers_200_response_users_inner(
                        _id = '', 
                        first_name = '', 
                        last_name = '', 
                        email = '', 
                        avatar = '', 
                        email_verified = True, 
                        role = '', 
                        custom_role = '', 
                        phone = '', 
                        phone_verified = True, 
                        last_login = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        is_active = True, 
                        account_status = 'pending', 
                        is_anonymous = True, 
                        created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        project = mudbase.models.get_organization_users_200_response_users_inner_project.getOrganizationUsers_200_response_users_inner_project(
                            _id = '', 
                            name = '', 
                            slug = '', ), )
                    ],
                total = 56,
                project = mudbase.models.get_organization_users_200_response_users_inner_project.getOrganizationUsers_200_response_users_inner_project(
                    _id = '', 
                    name = '', 
                    slug = '', )
            )
        else:
            return GetProjectUsers200Response(
        )
        """

    def testGetProjectUsers200Response(self):
        """Test GetProjectUsers200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
