# coding: utf-8

"""
    MUDBASESDK

    MUDBASE is a scalable, real-time, and secure Backend-as-a-Service (BaaS) platform  designed for modern applications. Built with custom logic, it offers fine-grained  control, extensibility, and enterprise-grade security.  ## Features - 🔐 Multi-provider authentication (30+ OAuth providers) - 📊 Real-time database with collections - 📁 File storage and management - 🔑 API key management with permissions - 🔗 Webhook system with retry logic - ⚡ Serverless functions - 💬 Multi-channel messaging (Push, Email, SMS) - 📈 Usage analytics and monitoring - 🌐 Real-time WebSocket events - 🔍 Full-text search capabilities - 💳 Billing: fiat only for project subscriptions and org BaaS checkout (platform fee split). On-chain billing is not exposed on these APIs (optional `crypto-payment-module/` in repo, not mounted by default). - 🏢 Enterprise / Phase 4: custom domains on Growth, Scale, and Enterprise (TXT DNS at `_mudbase-verify.<hostname>`); `settings.customDomainAddon` is optional (billing/legacy); dedicated DB migration script, periodic DNS recheck job, optional `infrastructureEnvironments[]` and edge/metering fields on `dedicated`. 

    The version of the OpenAPI document: 1.3.14
    Contact: support@mudbase.dev
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from mudbase.models.message_stats_response import MessageStatsResponse

class TestMessageStatsResponse(unittest.TestCase):
    """MessageStatsResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> MessageStatsResponse:
        """Test MessageStatsResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `MessageStatsResponse`
        """
        model = MessageStatsResponse()
        if include_optional:
            return MessageStatsResponse(
                success = True,
                data = mudbase.models.message_stats_response_data.MessageStatsResponse_data(
                    total_messages = 56, 
                    by_type = mudbase.models.message_stats_response_data_by_type.MessageStatsResponse_data_byType(
                        push = 56, 
                        email = 56, 
                        sms = 56, ), 
                    by_status = mudbase.models.message_stats_response_data_by_status.MessageStatsResponse_data_byStatus(
                        sent = 56, 
                        failed = 56, 
                        pending = 56, ), 
                    success_rate = 1.337, 
                    period = mudbase.models.message_stats_response_data_period.MessageStatsResponse_data_period(
                        start_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        end_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), ), )
            )
        else:
            return MessageStatsResponse(
        )
        """

    def testMessageStatsResponse(self):
        """Test MessageStatsResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
