# coding: utf-8

"""
    MUDBASESDK

    MUDBASE is a scalable, real-time, and secure Backend-as-a-Service (BaaS) platform  designed for modern applications. Built with custom logic, it offers fine-grained  control, extensibility, and enterprise-grade security.  ## Features - 🔐 Multi-provider authentication (30+ OAuth providers) - 📊 Real-time database with collections - 📁 File storage and management - 🔑 API key management with permissions - 🔗 Webhook system with retry logic - ⚡ Serverless functions - 💬 Multi-channel messaging (Push, Email, SMS) - 📈 Usage analytics and monitoring - 🌐 Real-time WebSocket events - 🔍 Full-text search capabilities - 💳 Billing: fiat only for project subscriptions and org BaaS checkout (platform fee split). On-chain billing is not exposed on these APIs (optional `crypto-payment-module/` in repo, not mounted by default). - 🏢 Enterprise / Phase 4: custom domains on Growth, Scale, and Enterprise (TXT DNS at `_mudbase-verify.<hostname>`); `settings.customDomainAddon` is optional (billing/legacy); dedicated DB migration script, periodic DNS recheck job, optional `infrastructureEnvironments[]` and edge/metering fields on `dedicated`. 

    The version of the OpenAPI document: 1.3.15
    Contact: support@mudbase.dev
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from mudbase.models.monitoring_analytics_response import MonitoringAnalyticsResponse

class TestMonitoringAnalyticsResponse(unittest.TestCase):
    """MonitoringAnalyticsResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> MonitoringAnalyticsResponse:
        """Test MonitoringAnalyticsResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `MonitoringAnalyticsResponse`
        """
        model = MonitoringAnalyticsResponse()
        if include_optional:
            return MonitoringAnalyticsResponse(
                period = '',
                granularity = '',
                days = 56,
                stats = [
                    mudbase.models.monitoring_analytics_response_stats_inner.MonitoringAnalyticsResponse_stats_inner(
                        date = '', 
                        api_calls = 56, 
                        db_reads = 56, 
                        db_writes = 56, 
                        storage = 56, 
                        bandwidth = 56, )
                    ],
                totals = mudbase.models.monitoring_analytics_response_totals.MonitoringAnalyticsResponse_totals(
                    total_api_calls = 56, 
                    total_db_reads = 56, 
                    total_db_writes = 56, 
                    total_storage = 56, 
                    total_bandwidth = 56, )
            )
        else:
            return MonitoringAnalyticsResponse(
        )
        """

    def testMonitoringAnalyticsResponse(self):
        """Test MonitoringAnalyticsResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
