# coding: utf-8

"""
    MUDBASESDK

    MUDBASE is a scalable, real-time, and secure Backend-as-a-Service (BaaS) platform  designed for modern applications. Built with custom logic, it offers fine-grained  control, extensibility, and enterprise-grade security.  ## Features - 🔐 Multi-provider authentication (30+ OAuth providers) - 📊 Real-time database with collections - 📁 File storage and management - 🔑 API key management with permissions - 🔗 Webhook system with retry logic - ⚡ Serverless functions - 💬 Multi-channel messaging (Push, Email, SMS) - 📈 Usage analytics and monitoring - 🌐 Real-time WebSocket events - 🔍 Full-text search capabilities - 💳 Billing: fiat only for project subscriptions and org BaaS checkout (platform fee split). On-chain billing is not exposed on these APIs (optional `crypto-payment-module/` in repo, not mounted by default). - 🏢 Enterprise / Phase 4: custom domains on Growth, Scale, and Enterprise (TXT DNS at `_mudbase-verify.<hostname>`); `settings.customDomainAddon` is optional (billing/legacy); dedicated DB migration script, periodic DNS recheck job, optional `infrastructureEnvironments[]` and edge/metering fields on `dedicated`. 

    The version of the OpenAPI document: 1.3.14
    Contact: support@mudbase.dev
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from mudbase.models.project import Project

class TestProject(unittest.TestCase):
    """Project unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Project:
        """Test Project
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Project`
        """
        model = Project()
        if include_optional:
            return Project(
                id = '',
                name = '',
                description = '',
                slug = '',
                org = '',
                auth = mudbase.models.auth_config.AuthConfig(
                    providers = [
                        mudbase.models.auth_provider.AuthProvider(
                            name = '', 
                            enabled = True, 
                            config = mudbase.models.config.config(), )
                        ], 
                    notify_on_new_sign_in = True, ),
                database = mudbase.models.database_config.DatabaseConfig(
                    collections = [
                        ''
                        ], ),
                storage = mudbase.models.storage_config.StorageConfig(
                    buckets = [
                        ''
                        ], ),
                settings = mudbase.models.project_settings.ProjectSettings(
                    allow_anonymous_auth = True, 
                    require_email_verification = True, 
                    require_phone_verification = True, 
                    default_user_account_status = 'active', 
                    enable_realtime = True, 
                    enable_storage = True, 
                    enable_functions = True, ),
                usage = mudbase.models.project_usage.ProjectUsage(
                    api_calls = 56, 
                    storage = 56, 
                    bandwidth = 56, 
                    db_reads = 56, 
                    db_writes = 56, ),
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f')
            )
        else:
            return Project(
        )
        """

    def testProject(self):
        """Test Project"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
