# coding: utf-8

"""
    MUDBASESDK

    MUDBASE is a scalable, real-time, and secure Backend-as-a-Service (BaaS) platform  designed for modern applications. Built with custom logic, it offers fine-grained  control, extensibility, and enterprise-grade security.  ## Features - 🔐 Multi-provider authentication (30+ OAuth providers) - 📊 Real-time database with collections - 📁 File storage and management - 🔑 API key management with permissions - 🔗 Webhook system with retry logic - ⚡ Serverless functions - 💬 Multi-channel messaging (Push, Email, SMS) - 📈 Usage analytics and monitoring - 🌐 Real-time WebSocket events - 🔍 Full-text search capabilities - 💳 Billing: fiat only for project subscriptions and org BaaS checkout (platform fee split). On-chain billing is not exposed on these APIs (optional `crypto-payment-module/` in repo, not mounted by default). - 🏢 Enterprise / Phase 4: custom domains on Growth, Scale, and Enterprise (TXT DNS at `_mudbase-verify.<hostname>`); `settings.customDomainAddon` is optional (billing/legacy); dedicated DB migration script, periodic DNS recheck job, optional `infrastructureEnvironments[]` and edge/metering fields on `dedicated`. 

    The version of the OpenAPI document: 1.3.12
    Contact: support@mudbase.dev
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from mudbase.models.org_domain_entry_org_console import OrgDomainEntryOrgConsole

class TestOrgDomainEntryOrgConsole(unittest.TestCase):
    """OrgDomainEntryOrgConsole unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> OrgDomainEntryOrgConsole:
        """Test OrgDomainEntryOrgConsole
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `OrgDomainEntryOrgConsole`
        """
        model = OrgDomainEntryOrgConsole()
        if include_optional:
            return OrgDomainEntryOrgConsole(
                id = '',
                hostname = '',
                status = '',
                is_primary = True,
                source = 'manual',
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                verified_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                last_verified_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                cname_submitted_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                cname_approved_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                custom_domain_verification_step = 56,
                routing_cname_target = '',
                dns_records = [
                    mudbase.models.org_dns_record.OrgDnsRecord(
                        type = '', 
                        name = '', 
                        value = '', 
                        purpose = '', )
                    ],
                platform_activation_pending = True,
                custom_domain_live_for_api_traffic = True,
                edge = mudbase.models.org_edge_hints.OrgEdgeHints(
                    saas_integration_enabled = True, 
                    skipped = True, 
                    reason = '', 
                    custom_hostname_id = '', 
                    hostname_status = '', 
                    ssl_status = '', 
                    ownership_verification = mudbase.models.org_edge_hints_ownership_verification.OrgEdgeHints_ownershipVerification(
                        name = '', 
                        type = '', 
                        value = '', ), 
                    ssl_validation_records = [
                        mudbase.models.org_ssl_validation_record.OrgSslValidationRecord(
                            txt_name = '', 
                            txt_value = '', 
                            http_url = '', 
                            http_body = '', 
                            cname = '', 
                            cname_target = '', )
                        ], 
                    last_error = '', 
                    instructions = '', ),
                fly_certificate_status = '',
                platform_dns_verification = mudbase.models.org_platform_dns_verification_customer.OrgPlatformDnsVerificationCustomer(
                    record_type = '', 
                    record_name = '', 
                    record_value = '', 
                    ttl_seconds = 56, 
                    staff_note = '', 
                    updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), ),
                platform_dns_verification_submitted_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f')
            )
        else:
            return OrgDomainEntryOrgConsole(
        )
        """

    def testOrgDomainEntryOrgConsole(self):
        """Test OrgDomainEntryOrgConsole"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
