# coding: utf-8

"""
    MUDBASESDK

    MUDBASE is a scalable, real-time, and secure Backend-as-a-Service (BaaS) platform  designed for modern applications. Built with custom logic, it offers fine-grained  control, extensibility, and enterprise-grade security.  ## Features - 🔐 Multi-provider authentication (30+ OAuth providers) - 📊 Real-time database with collections - 📁 File storage and management - 🔑 API key management with permissions - 🔗 Webhook system with retry logic - ⚡ Serverless functions - 💬 Multi-channel messaging (Push, Email, SMS) - 📈 Usage analytics and monitoring - 🌐 Real-time WebSocket events - 🔍 Full-text search capabilities - 💳 Billing: fiat only for project subscriptions and org BaaS checkout (platform fee split). On-chain billing is not exposed on these APIs (optional `crypto-payment-module/` in repo, not mounted by default). - 🏢 Enterprise / Phase 4: custom domains on Growth, Scale, and Enterprise (TXT DNS at `_mudbase-verify.<hostname>`); `settings.customDomainAddon` is optional (billing/legacy); dedicated DB migration script, periodic DNS recheck job, optional `infrastructureEnvironments[]` and edge/metering fields on `dedicated`. 

    The version of the OpenAPI document: 1.3.16
    Contact: support@mudbase.dev
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from mudbase.api.messaging_api import MessagingApi


class TestMessagingApi(unittest.TestCase):
    """MessagingApi unit test stubs"""

    def setUp(self) -> None:
        self.api = MessagingApi()

    def tearDown(self) -> None:
        pass

    def test_get_message_history(self) -> None:
        """Test case for get_message_history

        Get message history
        """
        pass

    def test_get_message_stats(self) -> None:
        """Test case for get_message_stats

        Get message statistics
        """
        pass

    def test_get_project_fcm_config(self) -> None:
        """Test case for get_project_fcm_config

        Get bring-your-own push credentials status (masked)
        """
        pass

    def test_get_project_sms_byo(self) -> None:
        """Test case for get_project_sms_byo

        Get BYO SMS provider configuration (masked)
        """
        pass

    def test_get_project_vapid_public_key(self) -> None:
        """Test case for get_project_vapid_public_key

        Get the Web Push public key (public)
        """
        pass

    def test_get_project_web_push_config(self) -> None:
        """Test case for get_project_web_push_config

        Get native Web Push (VAPID) configuration
        """
        pass

    def test_list_device_tokens(self) -> None:
        """Test case for list_device_tokens

        List registered device tokens
        """
        pass

    def test_list_web_push_subscriptions(self) -> None:
        """Test case for list_web_push_subscriptions

        List registered Web Push subscriptions
        """
        pass

    def test_patch_project_fcm_config(self) -> None:
        """Test case for patch_project_fcm_config

        Set or clear your own push service account (optional)
        """
        pass

    def test_patch_project_sms_byo(self) -> None:
        """Test case for patch_project_sms_byo

        Update BYO SMS provider credentials
        """
        pass

    def test_patch_project_web_push_config(self) -> None:
        """Test case for patch_project_web_push_config

        Update native Web Push (VAPID) configuration
        """
        pass

    def test_register_device_token(self) -> None:
        """Test case for register_device_token

        Register a device push token
        """
        pass

    def test_register_web_push_subscription(self) -> None:
        """Test case for register_web_push_subscription

        Register a browser Web Push subscription
        """
        pass

    def test_remove_web_push_subscription(self) -> None:
        """Test case for remove_web_push_subscription

        Unregister a Web Push subscription
        """
        pass

    def test_send_email(self) -> None:
        """Test case for send_email

        Send email
        """
        pass

    def test_send_push_notification(self) -> None:
        """Test case for send_push_notification

        Send push notification
        """
        pass

    def test_send_sms(self) -> None:
        """Test case for send_sms

        Send SMS
        """
        pass

    def test_unregister_device_token(self) -> None:
        """Test case for unregister_device_token

        Unregister a device push token
        """
        pass


if __name__ == '__main__':
    unittest.main()
