# coding: utf-8

"""
    MUDBASESDK

    MUDBASE is a scalable, real-time, and secure Backend-as-a-Service (BaaS) platform  designed for modern applications. Built with custom logic, it offers fine-grained  control, extensibility, and enterprise-grade security.  ## Features - 🔐 Multi-provider authentication (30+ OAuth providers) - 📊 Real-time database with collections - 📁 File storage and management - 🔑 API key management with permissions - 🔗 Webhook system with retry logic - ⚡ Serverless functions - 💬 Multi-channel messaging (Push, Email, SMS) - 📈 Usage analytics and monitoring - 🌐 Real-time WebSocket events - 🔍 Full-text search capabilities - 💳 Billing: fiat only for project subscriptions and org BaaS checkout (platform fee split). On-chain billing is not exposed on these APIs (optional `crypto-payment-module/` in repo, not mounted by default). - 🏢 Enterprise / Phase 4: custom domains on Growth, Scale, and Enterprise (TXT DNS at `_mudbase-verify.<hostname>`); `settings.customDomainAddon` is optional (billing/legacy); dedicated DB migration script, periodic DNS recheck job, optional `infrastructureEnvironments[]` and edge/metering fields on `dedicated`. 

    The version of the OpenAPI document: 1.3.14
    Contact: support@mudbase.dev
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from mudbase.models.create_plan_request import CreatePlanRequest

class TestCreatePlanRequest(unittest.TestCase):
    """CreatePlanRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreatePlanRequest:
        """Test CreatePlanRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreatePlanRequest`
        """
        model = CreatePlanRequest()
        if include_optional:
            return CreatePlanRequest(
                name = '',
                description = '',
                price = 1.337,
                currency = 'USD',
                interval = 'month',
                features = [
                    null
                    ],
                limits = mudbase.models.create_plan_request_limits.createPlan_request_limits(
                    api_calls = 1.337, 
                    storage = 1.337, 
                    bandwidth = 1.337, 
                    users = 1.337, 
                    custom_limits = [
                        mudbase.models.create_plan_request_limits_custom_limits_inner.createPlan_request_limits_customLimits_inner(
                            name = '', 
                            value = 1.337, )
                        ], ),
                trial = mudbase.models.create_plan_request_trial.createPlan_request_trial(
                    enabled = True, 
                    days = 1.337, ),
                is_active = True,
                is_default = True,
                sort_order = 1.337,
                metadata = { }
            )
        else:
            return CreatePlanRequest(
                name = '',
                price = 1.337,
                currency = 'USD',
                interval = 'month',
        )
        """

    def testCreatePlanRequest(self):
        """Test CreatePlanRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
