# coding: utf-8

"""
    MUDBASESDK

    MUDBASE is a scalable, real-time, and secure Backend-as-a-Service (BaaS) platform  designed for modern applications. Built with custom logic, it offers fine-grained  control, extensibility, and enterprise-grade security.  ## Features - 🔐 Multi-provider authentication (30+ OAuth providers) - 📊 Real-time database with collections - 📁 File storage and management - 🔑 API key management with permissions - 🔗 Webhook system with retry logic - ⚡ Serverless functions - 💬 Multi-channel messaging (Push, Email, SMS) - 📈 Usage analytics and monitoring - 🌐 Real-time WebSocket events - 🔍 Full-text search capabilities - 💳 Billing: fiat only for project subscriptions and org BaaS checkout (platform fee split). On-chain billing is not exposed on these APIs (optional `crypto-payment-module/` in repo, not mounted by default). - 🏢 Enterprise / Phase 4: custom domains on Growth, Scale, and Enterprise (TXT DNS at `_mudbase-verify.<hostname>`); `settings.customDomainAddon` is optional (billing/legacy); dedicated DB migration script, periodic DNS recheck job, optional `infrastructureEnvironments[]` and edge/metering fields on `dedicated`. 

    The version of the OpenAPI document: 1.3.14
    Contact: support@mudbase.dev
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from mudbase.models.add_custom_role_request import AddCustomRoleRequest

class TestAddCustomRoleRequest(unittest.TestCase):
    """AddCustomRoleRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AddCustomRoleRequest:
        """Test AddCustomRoleRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AddCustomRoleRequest`
        """
        model = AddCustomRoleRequest()
        if include_optional:
            return AddCustomRoleRequest(
                slug = 'seller',
                name = 'Seller',
                description = 'Seller role with CRUD on seller-owned collections',
                signup_endpoint = 'seller',
                requires_approval = False,
                requires_payment = False,
                requires_kyc = False,
                default_permissions = [
                    mudbase.models.add_custom_role_request_default_permissions_inner.addCustomRole_request_defaultPermissions_inner(
                        resource = '', 
                        actions = [
                            ''
                            ], )
                    ],
                collection_permissions = {
                    'key' : null
                    },
                metadata = None,
                feature_permissions = {"messaging":{"email":true,"sms":true,"push":false,"history":true,"stats":true},"integration":{"read":true,"execute":true},"storage":{"read":true,"upload":true}}
            )
        else:
            return AddCustomRoleRequest(
                slug = 'seller',
                name = 'Seller',
                signup_endpoint = 'seller',
        )
        """

    def testAddCustomRoleRequest(self):
        """Test AddCustomRoleRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
