# coding: utf-8

"""
    MUDBASESDK

    MUDBASE is a scalable, real-time, and secure Backend-as-a-Service (BaaS) platform  designed for modern applications. Built with custom logic, it offers fine-grained  control, extensibility, and enterprise-grade security.  ## Features - 🔐 Multi-provider authentication (30+ OAuth providers) - 📊 Real-time database with collections - 📁 File storage and management - 🔑 API key management with permissions - 🔗 Webhook system with retry logic - ⚡ Serverless functions - 💬 Multi-channel messaging (Push, Email, SMS) - 📈 Usage analytics and monitoring - 🌐 Real-time WebSocket events - 🔍 Full-text search capabilities - 💳 Billing: fiat only for project subscriptions and org BaaS checkout (platform fee split). On-chain billing is not exposed on these APIs (optional `crypto-payment-module/` in repo, not mounted by default). - 🏢 Enterprise / Phase 4: custom domains on Growth, Scale, and Enterprise (TXT DNS at `_mudbase-verify.<hostname>`); `settings.customDomainAddon` is optional (billing/legacy); dedicated DB migration script, periodic DNS recheck job, optional `infrastructureEnvironments[]` and edge/metering fields on `dedicated`. 

    The version of the OpenAPI document: 1.3.12
    Contact: support@mudbase.dev
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from mudbase.api.chat_api import ChatApi


class TestChatApi(unittest.TestCase):
    """ChatApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ChatApi()

    def tearDown(self) -> None:
        pass

    def test_add_participant(self) -> None:
        """Test case for add_participant

        Add participant to chat
        """
        pass

    def test_add_reaction(self) -> None:
        """Test case for add_reaction

        Add reaction to message
        """
        pass

    def test_create_chat(self) -> None:
        """Test case for create_chat

        Create new chat
        """
        pass

    def test_delete_message(self) -> None:
        """Test case for delete_message

        Delete message
        """
        pass

    def test_edit_message(self) -> None:
        """Test case for edit_message

        Edit message
        """
        pass

    def test_get_chat_details(self) -> None:
        """Test case for get_chat_details

        Get chat details
        """
        pass

    def test_get_chat_e2ee_participant_keys(self) -> None:
        """Test case for get_chat_e2ee_participant_keys

        List participant E2EE public keys
        """
        pass

    def test_get_chat_messages(self) -> None:
        """Test case for get_chat_messages

        Get chat messages
        """
        pass

    def test_get_user_chats(self) -> None:
        """Test case for get_user_chats

        Get user chats
        """
        pass

    def test_mark_messages_as_read(self) -> None:
        """Test case for mark_messages_as_read

        Mark messages as read
        """
        pass

    def test_put_chat_e2ee_key(self) -> None:
        """Test case for put_chat_e2ee_key

        Register chat E2EE identity public key
        """
        pass

    def test_remove_participant(self) -> None:
        """Test case for remove_participant

        Remove participant from chat
        """
        pass

    def test_remove_reaction(self) -> None:
        """Test case for remove_reaction

        Remove reaction from message
        """
        pass

    def test_send_message(self) -> None:
        """Test case for send_message

        Send message
        """
        pass


if __name__ == '__main__':
    unittest.main()
