# coding: utf-8

"""
    MUDBASESDK

    MUDBASE is a scalable, real-time, and secure Backend-as-a-Service (BaaS) platform  designed for modern applications. Built with custom logic, it offers fine-grained  control, extensibility, and enterprise-grade security.  ## Features - 🔐 Multi-provider authentication (30+ OAuth providers) - 📊 Real-time database with collections - 📁 File storage and management - 🔑 API key management with permissions - 🔗 Webhook system with retry logic - ⚡ Serverless functions - 💬 Multi-channel messaging (Push, Email, SMS) - 📈 Usage analytics and monitoring - 🌐 Real-time WebSocket events - 🔍 Full-text search capabilities - 💳 Billing: fiat only for project subscriptions and org BaaS checkout (platform fee split). On-chain billing is not exposed on these APIs (optional `crypto-payment-module/` in repo, not mounted by default). - 🏢 Enterprise / Phase 4: custom domains on Growth, Scale, and Enterprise (TXT DNS at `_mudbase-verify.<hostname>`); `settings.customDomainAddon` is optional (billing/legacy); dedicated DB migration script, periodic DNS recheck job, optional `infrastructureEnvironments[]` and edge/metering fields on `dedicated`. 

    The version of the OpenAPI document: 1.3.14
    Contact: support@mudbase.dev
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class DashboardOverviewDataLatencyInstanceRollup(BaseModel):
    """
    In-process p50/p95/p99 for this Node instance (ephemeral; multi-pod differs per replica)
    """ # noqa: E501
    scope: Optional[StrictStr] = None
    p50_ms: Optional[StrictInt] = Field(default=None, alias="p50Ms")
    p95_ms: Optional[StrictInt] = Field(default=None, alias="p95Ms")
    p99_ms: Optional[StrictInt] = Field(default=None, alias="p99Ms")
    mean_ms: Optional[StrictInt] = Field(default=None, alias="meanMs")
    samples_approx: Optional[StrictInt] = Field(default=None, alias="samplesApprox")
    templates_tracked: Optional[StrictInt] = Field(default=None, alias="templatesTracked")
    __properties: ClassVar[List[str]] = ["scope", "p50Ms", "p95Ms", "p99Ms", "meanMs", "samplesApprox", "templatesTracked"]

    @field_validator('scope')
    def scope_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['instance_recent']):
            raise ValueError("must be one of enum values ('instance_recent')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of DashboardOverviewDataLatencyInstanceRollup from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if p50_ms (nullable) is None
        # and model_fields_set contains the field
        if self.p50_ms is None and "p50_ms" in self.model_fields_set:
            _dict['p50Ms'] = None

        # set to None if p95_ms (nullable) is None
        # and model_fields_set contains the field
        if self.p95_ms is None and "p95_ms" in self.model_fields_set:
            _dict['p95Ms'] = None

        # set to None if p99_ms (nullable) is None
        # and model_fields_set contains the field
        if self.p99_ms is None and "p99_ms" in self.model_fields_set:
            _dict['p99Ms'] = None

        # set to None if mean_ms (nullable) is None
        # and model_fields_set contains the field
        if self.mean_ms is None and "mean_ms" in self.model_fields_set:
            _dict['meanMs'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of DashboardOverviewDataLatencyInstanceRollup from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "scope": obj.get("scope"),
            "p50Ms": obj.get("p50Ms"),
            "p95Ms": obj.get("p95Ms"),
            "p99Ms": obj.get("p99Ms"),
            "meanMs": obj.get("meanMs"),
            "samplesApprox": obj.get("samplesApprox"),
            "templatesTracked": obj.get("templatesTracked")
        })
        return _obj


