# coding: utf-8

"""
    MUDBASESDK

    MUDBASE is a scalable, real-time, and secure Backend-as-a-Service (BaaS) platform  designed for modern applications. Built with custom logic, it offers fine-grained  control, extensibility, and enterprise-grade security.  ## Features - 🔐 Multi-provider authentication (30+ OAuth providers) - 📊 Real-time database with collections - 📁 File storage and management - 🔑 API key management with permissions - 🔗 Webhook system with retry logic - ⚡ Serverless functions - 💬 Multi-channel messaging (Push, Email, SMS) - 📈 Usage analytics and monitoring - 🌐 Real-time WebSocket events - 🔍 Full-text search capabilities - 💳 Billing: fiat only for project subscriptions and org BaaS checkout (platform fee split). On-chain billing is not exposed on these APIs (optional `crypto-payment-module/` in repo, not mounted by default). - 🏢 Enterprise / Phase 4: custom domains on Growth, Scale, and Enterprise (TXT DNS at `_mudbase-verify.<hostname>`); `settings.customDomainAddon` is optional (billing/legacy); dedicated DB migration script, periodic DNS recheck job, optional `infrastructureEnvironments[]` and edge/metering fields on `dedicated`. 

    The version of the OpenAPI document: 1.3.13
    Contact: support@mudbase.dev
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt
from typing import Any, ClassVar, Dict, List, Optional
from mudbase.models.get_organization_users200_response_users_inner_project import GetOrganizationUsers200ResponseUsersInnerProject
from typing import Optional, Set
from typing_extensions import Self

class GetUserOverview200ResponseFootprint(BaseModel):
    """
    GetUserOverview200ResponseFootprint
    """ # noqa: E501
    file_count: Optional[StrictInt] = Field(default=None, alias="fileCount")
    storage_used: Optional[StrictInt] = Field(default=None, alias="storageUsed")
    session_count: Optional[StrictInt] = Field(default=None, alias="sessionCount")
    api_key_count: Optional[StrictInt] = Field(default=None, alias="apiKeyCount")
    collections_in_project: Optional[StrictInt] = Field(default=None, alias="collectionsInProject")
    collections: Optional[List[GetOrganizationUsers200ResponseUsersInnerProject]] = None
    __properties: ClassVar[List[str]] = ["fileCount", "storageUsed", "sessionCount", "apiKeyCount", "collectionsInProject", "collections"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of GetUserOverview200ResponseFootprint from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in collections (list)
        _items = []
        if self.collections:
            for _item_collections in self.collections:
                if _item_collections:
                    _items.append(_item_collections.to_dict())
            _dict['collections'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of GetUserOverview200ResponseFootprint from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "fileCount": obj.get("fileCount"),
            "storageUsed": obj.get("storageUsed"),
            "sessionCount": obj.get("sessionCount"),
            "apiKeyCount": obj.get("apiKeyCount"),
            "collectionsInProject": obj.get("collectionsInProject"),
            "collections": [GetOrganizationUsers200ResponseUsersInnerProject.from_dict(_item) for _item in obj["collections"]] if obj.get("collections") is not None else None
        })
        return _obj


