# coding: utf-8

"""
    MUDBASESDK

    MUDBASE is a scalable, real-time, and secure Backend-as-a-Service (BaaS) platform  designed for modern applications. Built with custom logic, it offers fine-grained  control, extensibility, and enterprise-grade security.  ## Features - 🔐 Multi-provider authentication (30+ OAuth providers) - 📊 Real-time database with collections - 📁 File storage and management - 🔑 API key management with permissions - 🔗 Webhook system with retry logic - ⚡ Serverless functions - 💬 Multi-channel messaging (Push, Email, SMS) - 📈 Usage analytics and monitoring - 🌐 Real-time WebSocket events - 🔍 Full-text search capabilities - 💳 Billing: fiat only for project subscriptions and org BaaS checkout (platform fee split). On-chain billing is not exposed on these APIs (optional `crypto-payment-module/` in repo, not mounted by default). - 🏢 Enterprise / Phase 4: custom domains on Growth, Scale, and Enterprise (TXT DNS at `_mudbase-verify.<hostname>`); `settings.customDomainAddon` is optional (billing/legacy); dedicated DB migration script, periodic DNS recheck job, optional `infrastructureEnvironments[]` and edge/metering fields on `dedicated`. 

    The version of the OpenAPI document: 1.3.16
    Contact: support@mudbase.dev
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from mudbase.models.mcp_config_get200_response_tools_inner import McpConfigGet200ResponseToolsInner
from typing import Optional, Set
from typing_extensions import Self

class McpConfigGet200Response(BaseModel):
    """
    McpConfigGet200Response
    """ # noqa: E501
    enabled: Optional[StrictBool] = None
    plan: Optional[StrictStr] = None
    allowed_plans: Optional[List[StrictStr]] = Field(default=None, alias="allowedPlans")
    free_promo_active: Optional[StrictBool] = Field(default=None, description="True if this org is on the free plan and MCP is temporarily enabled via the launch promo", alias="freePromoActive")
    free_promo_ends_at: Optional[datetime] = Field(default=None, description="When the free-plan MCP promo ends (null if not active)", alias="freePromoEndsAt")
    endpoint: Optional[StrictStr] = None
    tools: Optional[List[McpConfigGet200ResponseToolsInner]] = None
    __properties: ClassVar[List[str]] = ["enabled", "plan", "allowedPlans", "freePromoActive", "freePromoEndsAt", "endpoint", "tools"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of McpConfigGet200Response from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in tools (list)
        _items = []
        if self.tools:
            for _item_tools in self.tools:
                if _item_tools:
                    _items.append(_item_tools.to_dict())
            _dict['tools'] = _items
        # set to None if free_promo_ends_at (nullable) is None
        # and model_fields_set contains the field
        if self.free_promo_ends_at is None and "free_promo_ends_at" in self.model_fields_set:
            _dict['freePromoEndsAt'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of McpConfigGet200Response from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "enabled": obj.get("enabled"),
            "plan": obj.get("plan"),
            "allowedPlans": obj.get("allowedPlans"),
            "freePromoActive": obj.get("freePromoActive"),
            "freePromoEndsAt": obj.get("freePromoEndsAt"),
            "endpoint": obj.get("endpoint"),
            "tools": [McpConfigGet200ResponseToolsInner.from_dict(_item) for _item in obj["tools"]] if obj.get("tools") is not None else None
        })
        return _obj


