# coding: utf-8

"""
    MUDBASESDK

    MUDBASE is a scalable, real-time, and secure Backend-as-a-Service (BaaS) platform  designed for modern applications. Built with custom logic, it offers fine-grained  control, extensibility, and enterprise-grade security.  ## Features - 🔐 Multi-provider authentication (30+ OAuth providers) - 📊 Real-time database with collections - 📁 File storage and management - 🔑 API key management with permissions - 🔗 Webhook system with retry logic - ⚡ Serverless functions - 💬 Multi-channel messaging (Push, Email, SMS) - 📈 Usage analytics and monitoring - 🌐 Real-time WebSocket events - 🔍 Full-text search capabilities - 💳 Billing: fiat only for project subscriptions and org BaaS checkout (platform fee split). On-chain billing is not exposed on these APIs (optional `crypto-payment-module/` in repo, not mounted by default). - 🏢 Enterprise / Phase 4: custom domains on Growth, Scale, and Enterprise (TXT DNS at `_mudbase-verify.<hostname>`); `settings.customDomainAddon` is optional (billing/legacy); dedicated DB migration script, periodic DNS recheck job, optional `infrastructureEnvironments[]` and edge/metering fields on `dedicated`. 

    The version of the OpenAPI document: 1.3.13
    Contact: support@mudbase.dev
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from mudbase.models.org_domain_entry_org_console import OrgDomainEntryOrgConsole
from typing import Optional, Set
from typing_extensions import Self

class OrgDomainsListResponse(BaseModel):
    """
    OrgDomainsListResponse
    """ # noqa: E501
    domains: Optional[List[OrgDomainEntryOrgConsole]] = None
    dns_verification_instructions: Optional[StrictStr] = Field(default=None, description="Plain-language reminder to add the ownership TXT from each domain’s DNS checklist, then use Verify DNS in the organization’s domain settings.", alias="dnsVerificationInstructions")
    primary_hostname: Optional[StrictStr] = Field(default=None, alias="primaryHostname")
    api_base_url: Optional[StrictStr] = Field(default=None, alias="apiBaseUrl")
    max_domains: Optional[StrictInt] = Field(default=None, alias="maxDomains")
    custom_domain_allowed: Optional[StrictBool] = Field(default=None, alias="customDomainAllowed")
    __properties: ClassVar[List[str]] = ["domains", "dnsVerificationInstructions", "primaryHostname", "apiBaseUrl", "maxDomains", "customDomainAllowed"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of OrgDomainsListResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in domains (list)
        _items = []
        if self.domains:
            for _item_domains in self.domains:
                if _item_domains:
                    _items.append(_item_domains.to_dict())
            _dict['domains'] = _items
        # set to None if primary_hostname (nullable) is None
        # and model_fields_set contains the field
        if self.primary_hostname is None and "primary_hostname" in self.model_fields_set:
            _dict['primaryHostname'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of OrgDomainsListResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "domains": [OrgDomainEntryOrgConsole.from_dict(_item) for _item in obj["domains"]] if obj.get("domains") is not None else None,
            "dnsVerificationInstructions": obj.get("dnsVerificationInstructions"),
            "primaryHostname": obj.get("primaryHostname"),
            "apiBaseUrl": obj.get("apiBaseUrl"),
            "maxDomains": obj.get("maxDomains"),
            "customDomainAllowed": obj.get("customDomainAllowed")
        })
        return _obj


