# coding: utf-8

"""
    MUDBASESDK

    MUDBASE is a scalable, real-time, and secure Backend-as-a-Service (BaaS) platform  designed for modern applications. Built with custom logic, it offers fine-grained  control, extensibility, and enterprise-grade security.  ## Features - 🔐 Multi-provider authentication (30+ OAuth providers) - 📊 Real-time database with collections - 📁 File storage and management - 🔑 API key management with permissions - 🔗 Webhook system with retry logic - ⚡ Serverless functions - 💬 Multi-channel messaging (Push, Email, SMS) - 📈 Usage analytics and monitoring - 🌐 Real-time WebSocket events - 🔍 Full-text search capabilities - 💳 Billing: fiat only for project subscriptions and org BaaS checkout (platform fee split). On-chain billing is not exposed on these APIs (optional `crypto-payment-module/` in repo, not mounted by default). - 🏢 Enterprise / Phase 4: custom domains on Growth, Scale, and Enterprise (TXT DNS at `_mudbase-verify.<hostname>`); `settings.customDomainAddon` is optional (billing/legacy); dedicated DB migration script, periodic DNS recheck job, optional `infrastructureEnvironments[]` and edge/metering fields on `dedicated`. 

    The version of the OpenAPI document: 1.3.13
    Contact: support@mudbase.dev
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from mudbase.models.org_dns_record import OrgDnsRecord
from mudbase.models.org_edge_hints import OrgEdgeHints
from typing import Optional, Set
from typing_extensions import Self

class OrgVerifyCustomDomainDnsSuccessResponse(BaseModel):
    """
    OrgVerifyCustomDomainDnsSuccessResponse
    """ # noqa: E501
    success: StrictBool
    hostname: StrictStr
    status: StrictStr = Field(description="Domain row status after check (typically cname_pending_staff after first TXT success from pending/failed; legacy dns_verified possible)")
    verification_token: StrictStr = Field(alias="verificationToken")
    challenge_host: StrictStr = Field(description="Same as dnsTxtHost (_mudbase-verify.<hostname>)", alias="challengeHost")
    expected_txt: StrictStr = Field(description="Same as dnsTxtValue", alias="expectedTxt")
    dns_txt_host: StrictStr = Field(alias="dnsTxtHost")
    dns_txt_value: StrictStr = Field(alias="dnsTxtValue")
    edge: Optional[OrgEdgeHints] = None
    dns_records: Optional[List[OrgDnsRecord]] = Field(default=None, description="Same shape as `OrgDomainEntryWithDns.dnsRecords` when certificate provisioning ran after this successful verify; omit or empty when provisioning is disabled or not yet run.", alias="dnsRecords")
    fly_certificate_status: Optional[StrictStr] = Field(default=None, description="Managed certificate status after verify when provisioning is active; null otherwise", alias="flyCertificateStatus")
    fly_acme_enabled: Optional[StrictBool] = Field(default=None, description="True when automated managed-certificate provisioning is configured for this deployment.", alias="flyAcmeEnabled")
    fly_acme_disabled_reason: Optional[StrictStr] = Field(default=None, description="When `flyAcmeEnabled` is false, why automated provisioning did not run (ops misconfiguration hint).", alias="flyAcmeDisabledReason")
    fly_provision_error: Optional[StrictStr] = Field(default=None, description="When provisioning is enabled but certificate issuance failed, the provider error message for support; null on success.", alias="flyProvisionError")
    fly_legacy_staff_pipeline: Optional[StrictBool] = Field(default=None, description="When true, the legacy staff pipeline is on: status may stay `cname_pending_staff` and staff approve-cname is required even if certificate provisioning succeeds.", alias="flyLegacyStaffPipeline")
    __properties: ClassVar[List[str]] = ["success", "hostname", "status", "verificationToken", "challengeHost", "expectedTxt", "dnsTxtHost", "dnsTxtValue", "edge", "dnsRecords", "flyCertificateStatus", "flyAcmeEnabled", "flyAcmeDisabledReason", "flyProvisionError", "flyLegacyStaffPipeline"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of OrgVerifyCustomDomainDnsSuccessResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of edge
        if self.edge:
            _dict['edge'] = self.edge.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in dns_records (list)
        _items = []
        if self.dns_records:
            for _item_dns_records in self.dns_records:
                if _item_dns_records:
                    _items.append(_item_dns_records.to_dict())
            _dict['dnsRecords'] = _items
        # set to None if fly_certificate_status (nullable) is None
        # and model_fields_set contains the field
        if self.fly_certificate_status is None and "fly_certificate_status" in self.model_fields_set:
            _dict['flyCertificateStatus'] = None

        # set to None if fly_acme_disabled_reason (nullable) is None
        # and model_fields_set contains the field
        if self.fly_acme_disabled_reason is None and "fly_acme_disabled_reason" in self.model_fields_set:
            _dict['flyAcmeDisabledReason'] = None

        # set to None if fly_provision_error (nullable) is None
        # and model_fields_set contains the field
        if self.fly_provision_error is None and "fly_provision_error" in self.model_fields_set:
            _dict['flyProvisionError'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of OrgVerifyCustomDomainDnsSuccessResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "success": obj.get("success"),
            "hostname": obj.get("hostname"),
            "status": obj.get("status"),
            "verificationToken": obj.get("verificationToken"),
            "challengeHost": obj.get("challengeHost"),
            "expectedTxt": obj.get("expectedTxt"),
            "dnsTxtHost": obj.get("dnsTxtHost"),
            "dnsTxtValue": obj.get("dnsTxtValue"),
            "edge": OrgEdgeHints.from_dict(obj["edge"]) if obj.get("edge") is not None else None,
            "dnsRecords": [OrgDnsRecord.from_dict(_item) for _item in obj["dnsRecords"]] if obj.get("dnsRecords") is not None else None,
            "flyCertificateStatus": obj.get("flyCertificateStatus"),
            "flyAcmeEnabled": obj.get("flyAcmeEnabled"),
            "flyAcmeDisabledReason": obj.get("flyAcmeDisabledReason"),
            "flyProvisionError": obj.get("flyProvisionError"),
            "flyLegacyStaffPipeline": obj.get("flyLegacyStaffPipeline")
        })
        return _obj


