# coding: utf-8

"""
    MUDBASESDK

    MUDBASE is a scalable, real-time, and secure Backend-as-a-Service (BaaS) platform  designed for modern applications. Built with custom logic, it offers fine-grained  control, extensibility, and enterprise-grade security.  ## Features - 🔐 Multi-provider authentication (30+ OAuth providers) - 📊 Real-time database with collections - 📁 File storage and management - 🔑 API key management with permissions - 🔗 Webhook system with retry logic - ⚡ Serverless functions - 💬 Multi-channel messaging (Push, Email, SMS) - 📈 Usage analytics and monitoring - 🌐 Real-time WebSocket events - 🔍 Full-text search capabilities - 💳 Billing: fiat only for project subscriptions and org BaaS checkout (platform fee split). On-chain billing is not exposed on these APIs (optional `crypto-payment-module/` in repo, not mounted by default). - 🏢 Enterprise / Phase 4: custom domains on Growth, Scale, and Enterprise (TXT DNS at `_mudbase-verify.<hostname>`); `settings.customDomainAddon` is optional (billing/legacy); dedicated DB migration script, periodic DNS recheck job, optional `infrastructureEnvironments[]` and edge/metering fields on `dedicated`. 

    The version of the OpenAPI document: 1.3.12
    Contact: support@mudbase.dev
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
import pprint
from pydantic import BaseModel, ConfigDict, Field, StrictStr, ValidationError, field_validator
from typing import Any, List, Optional
from mudbase.models.patch_project_fcm_config_request_one_of import PatchProjectFcmConfigRequestOneOf
from mudbase.models.patch_project_fcm_config_request_one_of1 import PatchProjectFcmConfigRequestOneOf1
from pydantic import StrictStr, Field
from typing import Union, List, Set, Optional, Dict
from typing_extensions import Literal, Self

PATCHPROJECTFCMCONFIGREQUEST_ONE_OF_SCHEMAS = ["PatchProjectFcmConfigRequestOneOf", "PatchProjectFcmConfigRequestOneOf1"]

class PatchProjectFcmConfigRequest(BaseModel):
    """
    PatchProjectFcmConfigRequest
    """
    # data type: PatchProjectFcmConfigRequestOneOf
    oneof_schema_1_validator: Optional[PatchProjectFcmConfigRequestOneOf] = None
    # data type: PatchProjectFcmConfigRequestOneOf1
    oneof_schema_2_validator: Optional[PatchProjectFcmConfigRequestOneOf1] = None
    actual_instance: Optional[Union[PatchProjectFcmConfigRequestOneOf, PatchProjectFcmConfigRequestOneOf1]] = None
    one_of_schemas: Set[str] = { "PatchProjectFcmConfigRequestOneOf", "PatchProjectFcmConfigRequestOneOf1" }

    model_config = ConfigDict(
        validate_assignment=True,
        protected_namespaces=(),
    )


    def __init__(self, *args, **kwargs) -> None:
        if args:
            if len(args) > 1:
                raise ValueError("If a position argument is used, only 1 is allowed to set `actual_instance`")
            if kwargs:
                raise ValueError("If a position argument is used, keyword arguments cannot be used.")
            super().__init__(actual_instance=args[0])
        else:
            super().__init__(**kwargs)

    @field_validator('actual_instance')
    def actual_instance_must_validate_oneof(cls, v):
        instance = PatchProjectFcmConfigRequest.model_construct()
        error_messages = []
        match = 0
        # validate data type: PatchProjectFcmConfigRequestOneOf
        if not isinstance(v, PatchProjectFcmConfigRequestOneOf):
            error_messages.append(f"Error! Input type `{type(v)}` is not `PatchProjectFcmConfigRequestOneOf`")
        else:
            match += 1
        # validate data type: PatchProjectFcmConfigRequestOneOf1
        if not isinstance(v, PatchProjectFcmConfigRequestOneOf1):
            error_messages.append(f"Error! Input type `{type(v)}` is not `PatchProjectFcmConfigRequestOneOf1`")
        else:
            match += 1
        if match > 1:
            # more than 1 match
            raise ValueError("Multiple matches found when setting `actual_instance` in PatchProjectFcmConfigRequest with oneOf schemas: PatchProjectFcmConfigRequestOneOf, PatchProjectFcmConfigRequestOneOf1. Details: " + ", ".join(error_messages))
        elif match == 0:
            # no match
            raise ValueError("No match found when setting `actual_instance` in PatchProjectFcmConfigRequest with oneOf schemas: PatchProjectFcmConfigRequestOneOf, PatchProjectFcmConfigRequestOneOf1. Details: " + ", ".join(error_messages))
        else:
            return v

    @classmethod
    def from_dict(cls, obj: Union[str, Dict[str, Any]]) -> Self:
        return cls.from_json(json.dumps(obj))

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Returns the object represented by the json string"""
        instance = cls.model_construct()
        error_messages = []
        match = 0

        # deserialize data into PatchProjectFcmConfigRequestOneOf
        try:
            instance.actual_instance = PatchProjectFcmConfigRequestOneOf.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into PatchProjectFcmConfigRequestOneOf1
        try:
            instance.actual_instance = PatchProjectFcmConfigRequestOneOf1.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))

        if match > 1:
            # more than 1 match
            raise ValueError("Multiple matches found when deserializing the JSON string into PatchProjectFcmConfigRequest with oneOf schemas: PatchProjectFcmConfigRequestOneOf, PatchProjectFcmConfigRequestOneOf1. Details: " + ", ".join(error_messages))
        elif match == 0:
            # no match
            raise ValueError("No match found when deserializing the JSON string into PatchProjectFcmConfigRequest with oneOf schemas: PatchProjectFcmConfigRequestOneOf, PatchProjectFcmConfigRequestOneOf1. Details: " + ", ".join(error_messages))
        else:
            return instance

    def to_json(self) -> str:
        """Returns the JSON representation of the actual instance"""
        if self.actual_instance is None:
            return "null"

        if hasattr(self.actual_instance, "to_json") and callable(self.actual_instance.to_json):
            return self.actual_instance.to_json()
        else:
            return json.dumps(self.actual_instance)

    def to_dict(self) -> Optional[Union[Dict[str, Any], PatchProjectFcmConfigRequestOneOf, PatchProjectFcmConfigRequestOneOf1]]:
        """Returns the dict representation of the actual instance"""
        if self.actual_instance is None:
            return None

        if hasattr(self.actual_instance, "to_dict") and callable(self.actual_instance.to_dict):
            return self.actual_instance.to_dict()
        else:
            # primitive type
            return self.actual_instance

    def to_str(self) -> str:
        """Returns the string representation of the actual instance"""
        return pprint.pformat(self.model_dump())


